name = "SelfConsistentField"
uuid = "119f0ea8-998d-11e8-3b57-f9f0ca1c0560"
authors = ["Michael F. Herbst <info@michael-herbst.com>"]
version = "0.0.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
